### ISSUE TITLE
Relative date detection

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#101]
We will need this for invoices that contain words such as "prompt" (which will then allow me to finish up #77)

I think it would be better to discuss a little before I start building something completely unnecessary. Should this be a set of words that get detected in it's own detector and then get used in the date calculation file to calculate relations to other dates on the bill?

Would love your input @clemenshelm

**Comment by clemenshelm** [comment]
Yes.
