### ISSUE TITLE
Customer VAT number still recognized

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#103]
In bill ju6KkuS5SCy9HFJJx.pdf the customer's VAT number (ATU54441803) was recognized although it was passed to the recognizer. The bill attributes were:

```
{:customerId=>"CkgW2i3bKNLgEXqjL", :imageUrl=>"https://chillbill-prod.s3.eu-central-1.amazonaws.com/ju6KkuS5SCy9HFJJx.pdf", :status=>"uploaded", :direction=>"incoming", :paymentAccount=>{:type=>"cash", :name=>"Bargeld", :id=>"Dz7fHDNqoQvBSoKcJ", :accountNumber=>2700, :bookingSymbol=>"KA"}, :createdAt=>{:$date=>1480511449360}, :token=>"9MOROTfTDvaRsLkcIfbumSriGazRY72L2guv1ECY_Md", :isPaidInstantly=>false, :reviews=>[], :customerVatNumber=>"ATU54441803"}
```

**Comment by tamacodechi** [comment]
HMMMM, I think there's either something wrong with the retriever or with the way this bill was sent from the web app:
![screen shot 2016-12-13 at 16 20 28](https://cloud.githubusercontent.com/assets/5068494/21145908/2f02843c-c150-11e6-9c46-cd76b9f2effb.png)

**Comment by clemenshelm** [comment]
Do you pass the `customerVatNumber`?
