### ISSUE TITLE
Irish vat number not detected

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#147]
The vat number IE9692928F is not detected.

Bills:

- [x] GPtDdfL65GwhaP2sm.pdf
 - [x] gCjATsx9NFCgxssGh.pdf

**Comment by tamacodechi** [comment]
In both cases, it's an OCR thing 😑  However they are the nice kind of PDFs so maybe #62 might solve this eventually.
![screen shot 2017-01-19 at 14 09 14](https://cloud.githubusercontent.com/assets/5068494/22107921/e73955fe-de50-11e6-96d7-cbe1f50629ce.png)
