### ISSUE TITLE
Incorrect invoice date detected

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#182]
In the bill `ydqn6gT6vN8TnDwff.pdf` the invoice date is detected as 2016-01-17 when it is clearly written on the bill ![screen shot 2017-02-09 at 15 17 13](https://cloud.githubusercontent.com/assets/5068494/22787486/d34ea318-eedc-11e6-97aa-2108c4102a9b.png)

This bill's quality is not that great and the only other attribute detected is an incorrectly detected total amount, so it might well be an OCR issue. Would be nice to know what kind of words come out of this bill.

**Comment by Tr4in** [comment]
This is invoice date was recognized on a early version. On my version 15 it works fine!
