### ISSUE TITLE
The date for the duration of a bill is taken incorrectly as the invoice date

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#184]
In the bill `NbJitMpsnrBQvDpE4.PDF` the invoice date is recognized as `2007-02-01` instead of `2017-02-07 ` and the culprit is staring us right in the face 👀  
![screen shot 2017-02-09 at 16 04 04](https://cloud.githubusercontent.com/assets/5068494/22788870/81ff1c9a-eee1-11e6-97fa-ab615a414c5c.png)

Make sure this gets ignored ✌️

**Comment by Tr4in** [comment]
On my version 15 it gets correctly recognized.
