### ISSUE TITLE
Introduce new relative date terms

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#196]
In bills  
- [ ] 5wsQ7YppaZLN5FSGC.pdf
![bill 3](https://cloud.githubusercontent.com/assets/5068494/22972248/1dc40a1e-f379-11e6-9e11-274c605408b9.png)

- [ ] 9ynzhWf9nSxTrNmPu.pdf
![bill 4](https://cloud.githubusercontent.com/assets/5068494/22972247/1dbc4d2e-f379-11e6-8954-440b76842579.png)

we have this new relative date term. They're a bit different in these two cases but this principle is present in many other bills.

**Comment by tamacodechi** [comment]
Bonus discussion: How do we want to handle this principle? The same day as the invoice date? If a "sent on" date is present use that?

**Comment by Tr4in** [comment]
I would use invoice date.

**Comment by tamacodechi** [comment]
Oh yeah hehe sorry forgot to close the discussion. Yep, we're going with invoice date ;)
