### ISSUE TITLE
Due date taken as invoice date

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#208]
In bill `oAE4BBMHfDGfwhX3i.pdf` the invoice date is set to the due date, despite being clearly labelled .

**Comment by Tr4in** [comment]
The bug lies in max_words: 

words += find_dates(Word.all, SHORT_PERIOD_DATE_REGEX, max_words: 2)

With max_words: 1 the invoice date is correctly detected!

**Comment by tamacodechi** [comment]
Could you screenshot the output? Is it one word on there?
