### ISSUE TITLE
Improve OCR

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#210]
- [x] Read up on tesseract and see what's available for us to improve on
- [x] Gather known OCR issues and identify possible solutions

Bills with OCR issues:
- [OCR Issues](https://github.com/clemenshelm/chillbill-recognizer/issues?q=is%3Aopen+is%3Aissue+label%3AOCR)
- local cache of OCR issue bills

**Comment by mina1604** [comment]
Stop if it subjectively exceeds the given size

**Comment by clemenshelm** [comment]
We might need tesseract 4.0.0 which is not yet available through apt-get. There are instructions on how to compile it ourselves here: https://github.com/tesseract-ocr/tesseract/wiki/Compiling
