### ISSUE TITLE
Below and right_below are similar or redundant

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#212]
Right now we have below which detects things very much below a word. We NEED right_below for the invoice number recognition. Identify the discrepancies so the code doesn't have repetition and still suits our needs.

**Comment by Tr4in** [comment]
Example on bill rDxLnivxoXQw9nWa7.pdf:
![selection_006](https://user-images.githubusercontent.com/21169462/29606181-c3020090-87ed-11e7-84b2-fbd6c309af31.png)

Lets take 150,00 for example and call both methods:
![selection_007](https://user-images.githubusercontent.com/21169462/29606338-419385c8-87ee-11e7-958a-553cd7f9d736.png)
Completely different results

**Comment by Tr4in** [comment]
@clemenshelm the method **below** in dimensionable.rb does not return the word which is below. It just checks this **lower.right > current.left && lower != current** and not bottom and top!

**Comment by clemenshelm** [comment]
Yes, because so far that was enough 😉

**Comment by Tr4in** [comment]
@clemenshelm we should use right_below from now on

**Comment by clemenshelm** [comment]
Go for it!
