### ISSUE TITLE
3.0 recognized as price

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#217]
In bill kk4FafcZqvCCC64BY.pdf the string "3.0" is recognized as price. Make sure that numbers with only one decimal digit aren't recognized as prices.

**Comment by Tr4in** [comment]
**OLD:**
![selection_012](https://cloud.githubusercontent.com/assets/21169462/24933278/d3bb6426-1f15-11e7-9e48-157c61c29771.png)

**NEW:**
![selection_011](https://cloud.githubusercontent.com/assets/21169462/24933288/e21abb0c-1f15-11e7-9fde-8481d7935eed.png)
