### ISSUE TITLE
Address numbers recognized as prices

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#224]
In some bills parts of the adress are recognized as prices.

#### 24PC5D5oeL6fb8a5n.pdf

"13 902" is recognized as the price 13902.

<img width="127" alt="screen shot 2017-04-26 at 18 09 54" src="https://cloud.githubusercontent.com/assets/141632/25444487/a17628f6-2aab-11e7-835b-e27393d8d871.png">

#### 26joYiARG5L5SmfxM.pdf

"F14 302" is recognized as the price 14302.

<img width="345" alt="screen shot 2017-04-26 at 19 00 40" src="https://cloud.githubusercontent.com/assets/141632/25446753/d91fe8ee-2ab2-11e7-91eb-08ae1a952587.png">

#### 2kZogw6XHEKx5sxfe.pdf

"44 1160" is recognized as 44160. In this example it also looks like the coordinates aren't calculated correctly. The left coordinate should be the "leftest" of all words and the right coordinate should be the "rightest". Same for top and bottom.

<img width="812" alt="screen shot 2017-04-30 at 10 00 21" src="https://cloud.githubusercontent.com/assets/141632/25562645/0282fbaa-2d8c-11e7-9901-c7a70f11e5a6.png">

#### 2o8P5wJy9pTYaEbLo.pdf

"33 222" is recognized as price 33222.

<img width="165" alt="screen shot 2017-04-30 at 10 15 25" src="https://cloud.githubusercontent.com/assets/141632/25562721/1777f73e-2d8e-11e7-98cb-7c0648dbf482.png">

#### 2qZF2tx7qPXzTPFLt.pdf

"34 340" is recognized as price 34340.

<img width="171" alt="screen shot 2017-04-30 at 10 47 42" src="https://cloud.githubusercontent.com/assets/141632/25562978/7ef66888-2d92-11e7-9157-544b5436df04.png">

**Comment by Tr4in** [comment]
Looks good! Only 26joYiARG5L5SmfxM.pdf has to be fixed!

**Comment by tamacodechi** [comment]
Closed by #353
