### ISSUE TITLE
Negative prices are recognized as positive

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#228]
In bill 2D7BuHc3f8wAmb4y8.pdf, a price with a "-" prefix gets recognized as a positive price:

"-12,00" is recognized as 12,00.

<img width="116" alt="screen shot 2017-04-26 at 19 42 11" src="https://cloud.githubusercontent.com/assets/141632/25448415/a9140e5e-2ab8-11e7-97f7-c8a496112e9a.png">

Same issue in bill 2D9qX4We3PaFAYSMR.pdf:

<img width="119" alt="screen shot 2017-04-26 at 19 50 37" src="https://cloud.githubusercontent.com/assets/141632/25448726/b9a10708-2ab9-11e7-9e6f-463d40a41f2e.png">

**Comment by Thomas1e** [comment]
jY5WdQLB8DShKgrjT.pdf is another example
