### ISSUE TITLE
Bank account number recognized as price

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#229]
In bill 2HtXGWoynP3sFMvFH.pdf, part of the bank account number is recognized as price:

<img width="136" alt="screen shot 2017-04-26 at 20 01 40" src="https://cloud.githubusercontent.com/assets/141632/25449203/55de31b2-2abb-11e7-8398-b838e1e93803.png">

"27 900" is recognized as price 27900.

Also in bill 2X3ybPNqDbuwH5dSX.pdf the bank account number "2.654.580" is recognized as price 265458:

<img width="141" alt="screen shot 2017-04-29 at 21 48 05" src="https://cloud.githubusercontent.com/assets/141632/25558407/52968190-2d26-11e7-8840-d4eb64c35a8c.png">

**Comment by Tr4in** [comment]
On bill 2X3ybPNqDbuwH5dSX.pdf: 5,66 got recognized as price but its percent
