### ISSUE TITLE
UST Number recognized as price

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#230]
In bill 2JjDSP33hX6XMngHd.pdf, the UST number is recognized as price:

<img width="261" alt="screen shot 2017-04-26 at 20 06 52" src="https://cloud.githubusercontent.com/assets/141632/25449447/11122a10-2abc-11e7-85a3-925d182608cd.png">

"68 603" is recognized as price 68 603.

**Comment by tamacodechi** [comment]
Closed by #353
