### ISSUE TITLE
VAT number discovered as price

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#237]
In bill 2Q3jZFWCscBgqov2q.pdf a VAT number is discovered as price:

"77 967" is recognized as 77967.

<img width="333" alt="screen shot 2017-04-29 at 21 20 07" src="https://cloud.githubusercontent.com/assets/141632/25558212/27aa53c0-2d22-11e7-87f2-5679913d8e56.png">

**Comment by tamacodechi** [comment]
Closed by #353
