### ISSUE TITLE
Discount percent recognized as price

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#240]
In bill 2qZF2tx7qPXzTPFLt.pdf the discount percentage is recognized as prices:

<img width="96" alt="screen shot 2017-04-30 at 10 42 35" src="https://cloud.githubusercontent.com/assets/141632/25562925/c2a3aee8-2d91-11e7-99dc-8488ee831059.png">

**Comment by Thomas1e** [comment]
Another example BStaGs5GAwHCaYLaz.pdf

![bildschirmfoto vom 2017-08-17 12-55-27](https://user-images.githubusercontent.com/26839274/29409505-c37729b0-834c-11e7-9a57-953ef592c54b.png)
