### ISSUE TITLE
Hours recognized as prices

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#241]
In bill 2tMo5XaJRTcPwG55r.pdf, an amount of hours is recognized as price:

<img width="154" alt="screen shot 2017-04-30 at 10 58 08" src="https://cloud.githubusercontent.com/assets/141632/25563070/141f12d8-2d94-11e7-96fe-28a697af9c89.png">

**Comment by Thomas1e** [comment]
Another example BStaGs5GAwHCaYLaz.pdf

![bildschirmfoto vom 2017-08-17 12-55-27](https://user-images.githubusercontent.com/26839274/29409364-238c144c-834c-11e7-9707-25138eac0b04.png)
