### ISSUE TITLE
IBAN detected as a price

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#257]
**In bill `2WD644LZkqqBTAW5W.pdf`,
this part of an IBAN at the bottom:**
<img width="234" alt="screen shot 2017-05-10 at 14 34 37" src="https://cloud.githubusercontent.com/assets/5068494/25901624/96c85e00-3597-11e7-9889-fd8b9aeeac55.png">
**Gets detected and saved as a price term (bottom most price term):**
<img width="723" alt="screen shot 2017-05-10 at 14 34 24" src="https://cloud.githubusercontent.com/assets/5068494/25901625/9932d0a8-3597-11e7-8a5f-4aefb5d1014b.png">

Adjust the regex to stop this non-price from getting detected as a price please 🐻

**Comment by Tr4in** [comment]
New results ^^ :
![Selection_017.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57ed1d153450da0e00ddff0c/125516c66e82c728ace21e0d46db9196268197a080e78013f50ab2d86b56357c2301a03f32dfa17de8472950590b4bf9485d0d12fda88e2ba6e56e728b0903ffcd7f1d2598694ef1e1c84afd13b032884e8fb7b88344c7eb3821e18f8f493b0c48.png)
