### ISSUE TITLE
Improve deployment

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#261]
At the moment the deployment is a rake task. The problem with this is that all dependencies of all rake tasks are loaded which leads to some problems.

Please use a separate tool for deployment (like capistrano) to isolate it from the rake environment.

It would also be nice to commit, tag and push the newest version number created in the deployment. Make sure there are no uncommitted changes before deploying, though.

**Comment by tamacodechi** [comment]
There's also a guide for notifying rollbar about deployment  for auto resolving with capistrano:
https://rollbar.com/chillbill/chillbill-recognizer/deploys/
