### ISSUE TITLE
Save trimmed image offset from original for reviewers

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#270]
At some point in the future, it would be nice that the reviewers could see exactly where on the bill a recognized word comes from.

Since we use relative positioning from the trimmed image, and the reviewers view the original image, we need to be able to work with the data from the trimmed image on the original. 

**Note:** While poking around, we have found that rmagick's `.page` attribute method contains the offset of the trimmed image from the origin of the original.
eg.
<img width="257" alt="screen shot 2017-06-07 at 10 24 46" src="https://user-images.githubusercontent.com/5068494/26869749-d922ec98-4b6d-11e7-9e72-e23c86d3b796.png">

**Comment by clemenshelm** [comment]
As far as I understand it, this isn't necessary anymore now that we don't trim anymore 😄
