### ISSUE TITLE
VAT percent recognized as price

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#284]
In bill 7J4sSvSesAHz5bHyT.pdf the VAT percentage is recognized as price.

![Bildschirmfoto 2017-06-26 um 11.16.28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2169a778e3d0f005c2d9c/125516c66e82c728ace21e0d46ca9d96279180a186fbb245ab49ffd47b1676246454f56622d3a33db2022a50415e48b243504d58eeb9cb74fce36f34985619e8d6385d75c06914f9b1874de900eb278b4fd6e4be8b19c8fa2137a5dad11b61435c52dcbd4f3fb29a49c259f242e94953ac15326be274306e0a.png)

**Comment by Thomas1e** [comment]
Another example: hWtW3cWFwy842Ribr.pdf (I am not sure what "Auftragsvorlage" in this case means, but it increases the netto price). It was also recognized as price.

Another example: BStaGs5GAwHCaYLaz.pdf

![bildschirmfoto vom 2017-08-17 12-55-27](https://user-images.githubusercontent.com/26839274/29409583-354a1b10-834d-11e7-8ee1-c2b76b2f714c.png)
