### ISSUE TITLE
Pieces recognized as price

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#298]
In bill ihfDXTa64yYbFLa6Y.pdf the number of pieces is recognized as price.

<img width="122" alt="bildschirmfoto 2017-07-04 um 19 45 59" src="https://user-images.githubusercontent.com/141632/27839457-a9c0cd32-60f1-11e7-8d3e-a84462fc6b3b.png">

**Comment by Thomas1e** [comment]
Another example:
- 7Ny88dNNXKgYLdnbs.pdf (amount of hours - 50.00)
