### ISSUE TITLE
Different units recognized as prices

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#299]
In bill KGEFGTvogD5Ly9jTT.pdf many units are recognized as prices.

<img width="438" alt="bildschirmfoto 2017-07-04 um 19 51 50" src="https://user-images.githubusercontent.com/141632/27839575-90b34170-60f2-11e7-8e14-f636a77492e9.png">

**Comment by Thomas1e** [comment]
Another example:
- htEAZ3e4gBu3ZdLXN.pdf (0,75 is recognized as price several times)

**Comment by tamacodechi** [comment]
You could write an array of unit words and then reference it in parts like the PriceTerm where we reject anything that's next to Kg :v:

Something like `Word.right_above(self)&.text != Term::UNITS`
