### ISSUE TITLE
Undefined price found

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#300]
In bill 2AQDJZ5Nrhva2Qhug.pdf the price `111,11` is found although it's not part of the document.

**Comment by Tr4in** [comment]
The price 111,11 does not exist: 
![selection_020](https://user-images.githubusercontent.com/21169462/29381541-d0a7c816-82c9-11e7-9920-142e8d36917e.png)

Instead dates got recognized as prices: 
20.01 and 12.20

**Comment by Tr4in** [comment]
Changed after merge to: 
![selection_001](https://user-images.githubusercontent.com/21169462/29576284-9293bd94-8767-11e7-8f27-42d2ede47f17.png)

Easy going from now :sun_with_face:
