### ISSUE TITLE
adress recognized as prize

### ISSUE THREAD

**Issue by Thomas1e** [clemenshelm/chillbill-recognizer#302]
In JBBfpB9Fypf54hTz2.pdf and HaPoDhJqjpWRavh3h.pdf the adress 14 302 is recognized as price 14302,00.

![jbbfpb9fypf54htz2](https://user-images.githubusercontent.com/26839274/27864842-8d996d22-6190-11e7-9e28-d5b59f676364.png)

Other examples:
- iTGXBQoDzEsj8H54c

**Comment by tamacodechi** [comment]
Closed by #353
