### ISSUE TITLE
image cropping does not work correctly

### ISSUE THREAD

**Issue by Thomas1e** [clemenshelm/chillbill-recognizer#303]
ImageMagick cuts off too little:
LWhh572pQssaPRy8c.pdf

ImageMagick cuts off too much:
KRhAJaM8B2K6g6zfb.pdf  (the text on the bottom is brighter than the normal text)
wefxSb9dhwfJGHfpQ.pdf
w5DJLkKT8XNTrcG5q.pdf

**Comment by clemenshelm** [comment]
I'm closing this in favor of #310
