### ISSUE TITLE
Extend QR code parsing for multiple prices on one bill

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#309]
So far we don't have enough, or rather any, test data to write this feature but there are bills that contain multiple prices! ⛱  The QR code decoder should be able to return multiple prices in an array.

**Comment by clemenshelm** [comment]
Blocked until we've got sample data (will appear magically during reprocessing)

**Comment by clemenshelm** [comment]
Here are some examples:
- https://my.chillbill.co/bills/WGTPATXW4d2spmSok
- https://my.chillbill.co/bills/CmrXQAH7AnBdigwTB
- https://my.chillbill.co/bills/i4anwcZhDzPPLPBhL
