### ISSUE TITLE
Wrong text-box dimensions

### ISSUE THREAD

**Issue by Thomas1e** [clemenshelm/chillbill-recognizer#332]
The dimensions of the text-box are sometimes wrong. Maybe there are some "artifacts" recognized as text. 

Example bill: 
- 4gf87ndsAgDhTjZmg.pdf  (text_box_top = 0, which is incorrect)
- QcgqQs8d5bkLqs65q.pdf (text_box_bottom > 1!!)
- iLWtAEvMEtQw2bauv.pdf (text_box_left = 0!, should be around 0.05)
- T62xs4gCJ4WtCZrbh.pdf (text_box_right > 1!)
- bRrcBNr9ma9RnXoFT.pdf (text_box_bottom >1, text_box_right >1)

**Comment by clemenshelm** [comment]
Thanks for reporting! Just delete the test data on your machine if this happens and add the example here.

**Comment by tamacodechi** [comment]
Another good example that could help us filter out the "artefacts" is `iEXgdeSEdWnovb6j6.pdf`

When we inspect the height and width of all the present words, there are many very very small ones that may be artefacts, or may be single letters. We can definitely investigate and use this to filter them out.
