### ISSUE TITLE
lib/bill_recognizer.rb - long method with too many ABCs

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#39]
As we all know, our recognize method is massive and therefore needs refactoring:

```
lib/bill_recognizer.rb:36:3: C: Assignment Branch Condition size for recognize is too high. [67.3/15]
  def recognize
  ^^^
lib/bill_recognizer.rb:36:3: C: Method has too many lines. [71/10]
  def recognize 
  ^^^^^^^^^^^^^
```

We could compartmentalize the detection and the calculations seperately, or maybe seperate by feature? Maybe we could all discuss on here what we think is best (that was some day in the future when we look at it and wonder why the heck we did it that way we'll also have documentation behind our line of thinking 😆 )

**Comment by tamacodechi** [comment]
Just so I don't forget by tomorrow 😅  How bad an idea would it be for me to undertake these refactoring tasks during the holidays? It's getting a little annoying to have to deal with the rubocop to-do whenever we add anything to the recognizer (ie. almost every single issue hehehe), and it feels like at least I am just delaying the inevitable by not getting around to this.

Although, maybe it's more pressing to make the recognition better to make the bill processing better and that's why I haven't started this? (Totally an excuse, it actually terrifies me to start working on refactoring our really large methods)

**Comment by clemenshelm** [comment]
I think this would be a perfect holiday task 😄 

I thought the same thing today, it's getting a little annoying during the reviews to always have to look over the Rubocop changes.
