### ISSUE TITLE
lib/detectors/vat_number_detector.rb - long method with too many ABCs

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#43]
The find method is too long and might have to be refactored. This is actually caused by the linting, as some of the lines were too long and had to be split, it caused us to go one line over, making this method too long. _In this case it also has many ABCs because of the VAT number validation_.

```
lib/detectors/vat_number_detector.rb:21:3: C: Assignment Branch Condition size for find_vat_numbers is too high. [18.47/15]
  def self.find_vat_numbers(regex, after_each_word: nil)
  ^^^
lib/detectors/vat_number_detector.rb:21:3: C: Method has too many lines. [13/10]
  def self.find_vat_numbers(regex, after_each_word: nil) 
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Similar to #41 and #42

**Comment by tamacodechi** [comment]
Could we move the median sized text thing to dimensionable or word? Even though we only use it on the VAT number detection currently, I feel like it's not something specific/something that should be defined on the vat number detection.

**Comment by clemenshelm** [comment]
I think it should belong to `Word`, because it has only got dependencies on `Word`. So we should be able to call `Word.median_height`.
