### ISSUE TITLE
Add a version to the recognizer

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#52]
The recognizer should have a version number for each new version which gets deployed. This version number should automatically be generated in the deployment process and be sent with each recognition result so we can keep track in the web app which results were produced with which recognizer version.

**Comment by tamacodechi** [comment]
Hmmm... We are going to use [semantic versioning](http://semver.org/), right? Silly question, but which version are we currently on? Also since it can't automatically detect what kind of changes are being made on the deployment, the script should ask what kind of changes are being made, right?

**Comment by clemenshelm** [comment]
I think numbering it sequentially should be enough. Do you see an advantage in having a minor or patch version?

**Comment by tamacodechi** [comment]
Not really, except for doing things "the right way" 😅 
This makes things, a lot simpler though so it should be fine!

**Comment by clemenshelm** [comment]
Let's keep it simple for now. We can still move to semantic versioning once we need it.
