### ISSUE TITLE
Incorrect currency detected

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#70]
In invoices mMHiT2b3C5fgYqBzY.pdf and WHPRwa2CSgNDDrsx9.pdf USD is recognized, but the bill's currency is EUR.

**Comment by tamacodechi** [comment]
WHPRwa2CSgNDDrsx9.pdf is fixed but mMHiT2b3C5fgYqBzY.pdf has an OCR issue where a rogue $ sign is recognized that is not on the actual bill.
