### ISSUE TITLE
NoMethodError in BillRecognizer

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#76]
When a bill file is not a supported type, the `BillImageRetriever` returns `true` instead of a reference to the file (on line 38). The bill recognizer expects the returned object to have a `path` method, though. This causes the error

```
NoMethodError: undefined method `path' for true:TrueClass
/myapp/lib/bill_recognizer.rb:55:in `recognize'
```

Bill: xcaEpkmTauDsZz9fk.p7s

**Comment by tamacodechi** [comment]
Forgot to put that this was closed by #94 when I made the PR and it won't work retroactively 😅 

Just to reiterate:
Closed by #94
