### ISSUE TITLE
Recognize billing periods from labels

### ISSUE THREAD

**Issue by tamacodechi** [clemenshelm/chillbill-recognizer#79]
In the bill ```m4F2bLmpKn7wPqM7q.pdf``` the billing period is labeled by:

![screen shot 2016-11-11 at 11 58 36](https://cloud.githubusercontent.com/assets/5068494/20212946/39b88bf0-a806-11e6-8ab7-95d3acc26e0a.png)

We need to recognize in order to filter this out and get this bill to correctly return the invoice date.

**Comment by tamacodechi** [comment]
Hmm, I started working on this as two separate detectors, one for billing start labels and one for billing end labels, but I'm wondering if it wouldn't be better to detect both with one detector and as one kind of term and simply save each term with an attribute (start or end) and check for that in the date calculation? I think a little discussion about the design could save a lot of time of possibly redundant work 😉 

Maybe it's neater to keep them separate but it also means two separate detectors, tests for each, models for each and a table for each, and pretty much the same code (except for the regexes involved) being executed twice.

Thoughts @clemenshelm ?

**Comment by clemenshelm** [comment]
So far everything's in the billing period detector, right? I'd either do everything there or use the two detectors, otherwise we're introducing another system here (distinguishing terms by an attribute) which makes it probably harder to understand and more prone to errors.

**Comment by tamacodechi** [comment]
Hmm that makes sense, I think going with the two detectors sounds more correct, since the billing period detector detects billing periods not billing period labels. Or am I being too pedantic? 😅

**Comment by clemenshelm** [comment]
I think you’re right. If there's a lot of duplication, we can still refactor it later on.
