### ISSUE TITLE
Super future invoice date

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#89]
In bill p6eYWvCeXyeApYB7t.pdf the invoice date gets recognized as 4510-10-24. I'm not quite sure why, probably the text recognition for the billing period is wrong. If that's the case, we can't do much about it (yet). Still it would be a good idea to prevent invoice dates so far ahead in the future from being recognized.

**Comment by tamacodechi** [comment]
Silly question but would it be an okay idea to limit the regex for the dates (and years in the dates specifically) to the current millennium and century at least?

**Comment by clemenshelm** [comment]
Not a silly question. Yes, that would make perfect sense!
